name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Lint (staticcheck)
      run: go install honnef.co/go/tools/cmd/staticcheck@latest && staticcheck ./...

    - name: Build
      run: go build -v ./...